version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./src/main/resources/bank-transactions.txt:/opt/kafka/bank-transactions.txt
      - ./src/main/resources/user-purchases.txt:/opt/kafka/user-purchases.txt
      - ./src/main/resources/user-table.txt:/opt/kafka/user-table.txt