version: "3.7"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: word-count-input:2:1,word-count-output:2:1,favorite-color-input:2:1,favorite-color-output:2:1,favorite-color-keyed:2:1
